import localFont from "next/font/local";
import "../globals.css";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";
import initTranslations from "../i18n";
import TranslationsProvider from "@/components/TranslationsProvider";
import { dir } from "i18next";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


const i18nNamespaces = ["home"];

export default async function RootLayout({ children, params }) {

  const { locale } = params;

  const { resources, t } = await initTranslations(locale, i18nNamespaces);

  return (
    <html lang={locale} dir={dir(locale)} >
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

        <TranslationsProvider
          namespaces={i18nNamespaces}
          locale={locale}
          resources={resources}
        >

          <NavBar />
          {children}
          <Footer params={params} />


        </TranslationsProvider>
      </body>
    </html>
  );
}
